[package]
name = "subzey/fizzbuzz"
version = "1.0.1"
description = "Prints out FizzBuzz, see https://en.wikipedia.org/wiki/Fizz_buzz"
license = "WTFPL"
repository = "https://github.com/subzey/wasi-fizzbuzz"
readme = "readme.md"

[[module]]
name = "fizzbuzz"
source = "fizzbuzz.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "fizzbuzz"
module = "fizzbuzz"
